version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8082:8082"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      MYSQL_DATABASE: ${MYSQL_DATABASE} # These are no longer used for connection
      MYSQL_USER: ${MYSQL_USER}       # but might be used for other config
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} #
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    depends_on:
      # - mysql # Removed
      # - redis # Removed

  frontend:
    build:
      context: ./client/jwt-auth-client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

# volumes: # Removed as we are using managed services
#   mysql-data:
